# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7efe1fe7647c641109844f23a6cddebe"
application_url = "https://dentists-img-considers-listen.trycloudflare.com"
embedded = true
name = "data-sync-app"
handle = "data-sync-app-5"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/orders_create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/app/products_update"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://dentists-img-considers-listen.trycloudflare.com/auth/callback",
  "https://dentists-img-considers-listen.trycloudflare.com/auth/shopify/callback",
  "https://dentists-img-considers-listen.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
